version: "3.7"
services:
  api_service:
    environment:
      gmail_api: ${gmail_api}
    build: .
    restart: always
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:latest"
    restart: always
    ports:
      - "127.0.0.1:27017:27017"