name: Maven Dependency Tree Dependency Submission
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  scan:
    steps:
     - uses: advanced-security/maven-dependency-submission-action@v3.0.0
     - name: Scan dependencies
